### PR TITLE
Patch 1 Kerlink.md

### PR DESCRIPTION
**Pull request by activiteOCR**
Add details to install wirnet IoT station (Julien Terrier).

### CODE REVIEW

**Comment by brocaar** [comment]
Thanks @activiteOCR :+1:

**Comment by activiteOCR** [comment]
Hello,
I saw two mistakes, line 84 we can delete #mosquitto and line 89 and 91 change 5. by 7. and 6. by 8.
There is also an error with balise {{< /highlight >}} before last line, sorry.

**Comment by brocaar** [comment]
@activiteOCR would you mind creating a new pull-request with these changes?

**Comment by activiteOCR** [comment]
Sure just I'm waiting then answer of that [https://forum.chirpstack.io/t/chirpstack-gateway-bridge-on-kerlink-iot-station/6751] to corrige this trouble :)

**Pull request merged**
